services:
  piquel-docs:
    image: ghcr.io/piquelorganization/docs.piquel.fr:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.piquel-api.loadbalancer.server.port=80"
      - "traefik.http.routers.piquel-api.rule=Host(`${HOST}`)"
      - "traefik.http.routers.piquel-api.entrypoints=piquel-https"
      - "traefik.http.routers.piquel-api.tls.certresolver=piquel-resolver"
    environment:
      DOMAIN: ${DOMAIN}
      HOST: ${HOST}
    deploy:
      update_config:
        order: start-first
    networks:
      - piquel-network

networks:
  piquel-network:
    external: true
    name: piquel-network
