name: Build and Deploy
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - '.air.toml'
      - 'README.md'
      - 'Makefile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/piquelorganization/docs.piquel.fr:latest
            ghcr.io/piquelorganization/docs.piquel.fr:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "DOMAIN=${{ vars.DOMAIN }}" >> ./.env
          echo "HOST=${{ vars.HOST }}" >> ./.env
          echo "REPOSITORY=${{ vars.REPOSITORY }}" >> ./.env
          echo "WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}" >> ./.env

          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./.env

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: piquel-docs
          file: docker-stack.yml
          host: piquel.fr
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./.env

