name: Build

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.air.toml'
      - 'README.md'
      - 'Makefile'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.air.toml'
      - 'README.md'
      - 'Makefile'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Build the Server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build the service
        run: |
          go build -o bin/docs main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ github.sha }}
          path: bin/
